[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Theme]
Current=featheros
CursorTheme=breeze_cursors
Font=Inter,11,-1,5,50,0,0,0,0,0

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastUser=true
RememberLastSession=true

